---
run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
  disable:
    - errcheck      # TODO: Enable and fix unchecked errors
    - gocyclo       # TODO: Refactor complex functions
    - gocritic      # TODO: Enable for style improvements
    - staticcheck   # TODO: Fix deprecated APIs and style issues
    - unused        # TODO: Clean up unused code

linters-settings:
  gocyclo:
    min-complexity: 50  # Very lenient for now

  govet:
    disable:
      - printf  # Disable printf analysis - we use color.Sprintf with dynamic strings intentionally

issues:
  exclude-rules:
    # Ignore format string warnings for color library usage
    - linters:
        - govet
      text: "non-constant format string"
